### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by MisterRayman** [imzbf/md-editor-v3#716]
### Describe the issue

I've got a Vue3 Project where I switched to your md-editor. Sometimes when _quickly switching between components_ I get the following error:
> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll') at index.mjs:2276:20

When following the code the error come from the following line: 
> zoomMermaid(rootRef.value.querySelectorAll(`#${editorId} .${prefix}-mermaid`));

Even when noMermaid is set to true, the error still appears.

After some investigation it looks like the .value can sometimes still be undefined, causing the error to appear.
> index.mjs:2273 rootRef: RefImpl {dep: Dep, __v_isRef: true, __v_isShallow: false, _rawValue: null, _value: null}dep: Dep {computed: undefined, version: 2, activeLink: undefined, subs: undefined, map: undefined, …}__v_isRef: true__v_isShallow: false_rawValue: null_value: nullvalue: (...)[[Prototype]]: Object
>
>index.mjs:2275 rootRef.value: null

When the value is set (the error doesn't appear) everything works perfectly.

This is how I implemented the editor into my component:
```vue 
<template>
    <MdEditor language="de-DE" v-model="textModel" :toolbars="whitelist" noUploadImg="true" noMermaid="true"/>
</template>

<script setup>
import { MdEditor, config } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
import DE_DE from '@vavt/cm-extension/dist/locale/de-DE';

const textModel = defineModel();

const whitelist = [
    "title",
    "-",
    "bold", "italic", "strikeThrough",
    "-",
    "unorderedList", "orderedList", "quote", "link", "image",
    "-",
    "revoke", "next", "prettier",
    "=",
    "pageFullscreen", "fullscreen", "preview", "previewOnly"
];

config({
    editorConfig: {
        languageUserDefined: {
            'de-DE': DE_DE
        },
    }
});
</script>

<script>
export default {
    name: 'MarkdownEditor',
};
</script>
```

### Procedure version

nodejs: 22.11.0, vue: 3.5.12, md-editor-v3: 5.0.1

**Comment by imzbf** [comment]
Please provide a demo project to restore the problem. The above code is not enough.

**Comment by MisterRayman** [comment]
Please try this repo [https://github.com/MisterRayman/DemoBug](https://github.com/MisterRayman/DemoBug) as the demo project.

**Comment by liujianglc** [comment]
zoomMermaid(rootRef.value.querySelectorAll(`#${editorId} .${prefix}-mermaid`)),  rootRef.value is null

**Comment by imzbf** [comment]
Fixed in 5.0.2

**Comment by MisterRayman** [comment]
Sorry to bother you again. Could you check if your fix works for the demo project? Locally I still get the error even after updating to 5.0.2.

**Comment by imzbf** [comment]
> Sorry to bother you again. Could you check if your fix works for the demo project? Locally I still get the error even after updating to 5.0.2.

em. I didn't find this issue in the demo project. Are there any other operations?

https://github.com/user-attachments/assets/eadb670f-f78b-4aa5-9d2c-c8a4e96c3758

**Comment by MisterRayman** [comment]
Ah sorry it seems to be a problem with the original project. The demo works fine with the update. I have no idea why i doesn't seem to be working for the original project. Consider this closed. I'll let you know if/when I find a way to reproduce the error in the demo project. 
Thank you for the quick responses!

**Comment by liujianglc** [comment]
After updated 5.0.2 , still have the problem.

![image](https://github.com/user-attachments/assets/0307a162-273b-423d-ba20-bb12a9ba3c2b)
![image](https://github.com/user-attachments/assets/62e001c9-d8a9-4a6b-a154-7b9b3e5217fb)
![image](https://github.com/user-attachments/assets/3dd1ae43-a612-4e9f-9809-90565e64233f)

**Comment by imzbf** [comment]
I need a demo project. Although the null value can be determined directly in the code, the fundamental problem has not been solved.

**Comment by karberlee** [comment]
> I need a demo project. Although the null value can be determined directly in the code, the fundamental problem has not been solved.

The examples in the official documentation can be reproduced directly

![image](https://github.com/user-attachments/assets/68aeff63-5dba-4d12-935b-508b07d57ece)
![image](https://github.com/user-attachments/assets/264db040-f267-40b1-a68a-fb2e3273980b)
![image](https://github.com/user-attachments/assets/f3baabdc-b499-4b17-92d0-5e88545ed67a)

**Comment by karberlee** [comment]
> > I need a demo project. Although the null value can be determined directly in the code, the fundamental problem has not been solved.
> 
> The examples in the official documentation can be reproduced directly
> 
> ![image](https://private-user-images.githubusercontent.com/59903832/388443629-68aeff63-5dba-4d12-935b-508b07d57ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzkzNDAsIm5iZiI6MTczMjIzOTA0MCwicGF0aCI6Ii81OTkwMzgzMi8zODg0NDM2MjktNjhhZWZmNjMtNWRiYS00ZDEyLTkzNWItNTA4YjA3ZDU3ZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAxMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYmE2N2ZiOTI3OTI5ZjQxNzlmZDQzMWExYTk1YmVlNGJlZGRjMzAzZGE3ODA1MGY1YzBmZjUxMmRlZWNjNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sKXFbrexpMiflr0rtLd3rQU9isdgMeR-KDf2_pGlvqM) ![image](https://private-user-images.githubusercontent.com/59903832/388444863-264db040-f267-40b1-a68a-fb2e3273980b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzkzNDAsIm5iZiI6MTczMjIzOTA0MCwicGF0aCI6Ii81OTkwMzgzMi8zODg0NDQ4NjMtMjY0ZGIwNDAtZjI2Ny00MGIxLWE2OGEtZmIyZTMyNzM5ODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAxMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OWIxMjhkYjM3OTI0MWZkZTYxNTZiZGY1MWMzNTc5NTkwODM1NTAwYTMyMzVhNzc1NjY3M2JlNDExYjdiZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x3OwrQTHnEpWtgeprSfLipfT5Red0VhU5byaB_GxIpM) ![image](https://private-user-images.githubusercontent.com/59903832/388443361-f3baabdc-b499-4b17-92d0-5e88545ed67a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzkzNDAsIm5iZiI6MTczMjIzOTA0MCwicGF0aCI6Ii81OTkwMzgzMi8zODg0NDMzNjEtZjNiYWFiZGMtYjQ5OS00YjE3LTkyZDAtNWU4ODU0NWVkNjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAxMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOWU3ZDZhMTZhYTBkOTUyYmMyMGNlZWQ3MmU5Mzk1ZjZjYTgzMDI0NTY1ODJhMWIxYmVlMmU0NTQ5YWRhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.etG-1Ps3DFAuhI61hESUTjWkAx4bWKQHB1KcacIj4AQ)

I fixed it by set editorId="md-editor-v-0"
![image](https://github.com/user-attachments/assets/2a072e2c-3fff-449b-95fa-532d3849bc8f)

**Comment by imzbf** [comment]
The value returned by `useId` in the new version of `Vue` has changed from `v:0` to `v-0`. Therefore, upgrading `Vue` is all that is needed.

**Comment by imzbf** [comment]
at least [3.5.3](https://github.com/vuejs/core/blob/main/CHANGELOG.md#353-2024-09-06)

**Comment by karberlee** [comment]
Already tried, Vue 3.5.0 will report an error, but can let it work set editorId="md-editor-v-0". 3.5.12 runs normally.

**Comment by karberlee** [comment]
Already tried, Vue 3.5.0 will report an error, but can let it work set editorId="md-editor-v-0". 3.5.12 runs normally.
